<a href="https://colab.research.google.com/github/Thanushreecj/MLC_activities/blob/main/WSS_CWE_vs_CVE.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# import packages
import pandas as pd
import os
import re

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
DIR='/content/drive/My Drive/Colab Notebooks/data'
datafile='699.csv'
filename=DIR+'/'+datafile

In [ ]:
os.chdir(DIR)
df = pd.read_csv(datafile)
df

,CWE-ID,Name,Weakness Abstraction,Status,Description,Extended Description,Related Weaknesses,Weakness Ordinalities,Applicable Platforms,Background Details,...,Likelihood of Exploit,Common Consequences,Detection Methods,Potential Mitigations,Observed Examples,Functional Areas,Affected Resources,Taxonomy Mappings,Related Attack Patterns,Notes
15,External Control of System or Configuration Se...,Base,Incomplete,One or more system settings or configuration e...,Allowing external control of system settings c...,::NATURE:ChildOf:CWE ID:642:VIEW ID:1000:ORDIN...,::ORDINALITY:Primary::,::TECHNOLOGY CLASS:Not Technology-Specific:TEC...,NaN,NaN,...,::SCOPE:Other:IMPACT:Varies by Context::,::METHOD:Automated Static Analysis:DESCRIPTION...,::PHASE:Architecture and Design:STRATEGY:Separ...,NaN,NaN,NaN,::TAXONOMY NAME:7 Pernicious Kingdoms:ENTRY NA...,::13::146::176::203::270::271::579::69::76::77::,NaN,NaN
22,Improper Limitation of a Pathname to a Restric...,Base,Stable,The product uses external input to construct a...,Many file operations are intended to take plac...,::NATURE:ChildOf:CWE ID:706:VIEW ID:1000:ORDIN...,::ORDINALITY:Primary::ORDINALITY:Resultant::,::LANGUAGE CLASS:Not Language-Specific:LANGUAG...,NaN,::TERM:Directory traversal::TERM:Path traversa...,...,::SCOPE:Integrity:SCOPE:Confidentiality:SCOPE:...,::METHOD:Automated Static Analysis:DESCRIPTION...,::PHASE:Implementation:STRATEGY:Input Validati...,::REFERENCE:CVE-2024-37032:DESCRIPTION:Large l...,::File Processing::,::File or Directory::,::TAXONOMY NAME:PLOVER:ENTRY NAME:Path Travers...,::126::64::76::78::79::,::TYPE:Other:NOTE:In many programming language...,NaN
41,Improper Resolution of Path Equivalence,Base,Incomplete,The product is vulnerable to file system conte...,Path equivalence is usually employed in order ...,::NATURE:ChildOf:CWE ID:706:VIEW ID:1000:ORDIN...,::ORDINALITY:Primary::,::LANGUAGE CLASS:Not Language-Specific:LANGUAG...,NaN,NaN,...,::SCOPE:Confidentiality:SCOPE:Integrity:SCOPE:...,::METHOD:Automated Static Analysis - Binary or...,::PHASE:Implementation:STRATEGY:Input Validati...,::REFERENCE:CVE-2000-1114:DESCRIPTION:Source c...,::File Processing::,::File or Directory::,::TAXONOMY NAME:PLOVER:ENTRY NAME:Path Equival...,::3::,::TYPE:Relationship:NOTE:Some of these manipul...,NaN
59,Improper Link Resolution Before File Access ('...,Base,Draft,The product attempts to access a file based on...,NaN,::NATURE:ChildOf:CWE ID:706:VIEW ID:1000:ORDIN...,::ORDINALITY:Resultant::,::LANGUAGE CLASS:Not Language-Specific:LANGUAG...,::Soft links are a UNIX term that is synonymou...,::TERM:insecure temporary file:DESCRIPTION:Som...,...,::SCOPE:Confidentiality:SCOPE:Integrity:SCOPE:...,::METHOD:Automated Static Analysis - Binary or...,::PHASE:Architecture and Design:STRATEGY:Separ...,::REFERENCE:CVE-1999-1386:DESCRIPTION:Some ver...,::File Processing::,::File or Directory::,::TAXONOMY NAME:PLOVER:ENTRY NAME:Link Followi...,::132::17::35::76::,::TYPE:Theoretical:NOTE:Link following vulnera...,NaN
66,Improper Handling of File Names that Identify ...,Base,Draft,The product does not handle or incorrectly han...,Virtual file names are represented like normal...,::NATURE:ChildOf:CWE ID:706:VIEW ID:1000:ORDIN...,::ORDINALITY:Primary::ORDINALITY:Resultant::,::LANGUAGE CLASS:Not Language-Specific:LANGUAG...,NaN,NaN,...,::SCOPE:Other:IMPACT:Other::,::METHOD:Automated Static Analysis - Binary or...,NaN,"::REFERENCE:CVE-1999-0278:DESCRIPTION:In IIS, ...",::File Processing::,::File or Directory::,::TAXONOMY NAME:PLOVER:ENTRY NAME:Virtual Files::,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1335,Incorrect Bitwise Shift of Integer,Base,Draft,An integer value is specified to be shifted by...,Specifying a value to be shifted by a negative...,::NATURE:ChildOf:CWE ID:682:VIEW ID:1000:ORDIN...,::ORDINALITY:Primary::,::LANGUAGE NAME:C:LANGUAGE PREVALENCE:Undeterm...,NaN,NaN,...,"::SCOPE:Integrity:IMPACT:DoS: Crash, Exit, or ...",::METHOD:Automated Static Analysis:DESCRIPTION...,::PHASE:Implementation:DESCRIPTION:Implicitly ...,::REFERENCE:CVE-2009-4307:DESCRIPTION:An unexp...,NaN,NaN,NaN,NaN,NaN,NaN
1339,Insufficient Precision or Accuracy of a Real N...,Base,Draft,The product processes a real number with an im...,When a security decision or calculation requir...,::NATURE:ChildOf:CWE ID:682:VIEW ID:1000:ORDIN...,::ORDINALITY:Primary::,::LANGUAGE CLASS:Not Language-Specific:LANGUAG...,::There are three major ways to store real num...,NaN,...,"::SCOPE:Availability:IMPACT:DoS: Crash, Exit, ...",::METHOD:Automated Static Analysis:DESCRIPTION...,::PHASE:Implementation Patching and Maintenanc...,::REFERENCE:CVE-2018-16069:DESCRIPTION:Chain: ...,NaN,NaN,NaN,NaN,NaN,NaN
1341,Multiple Releases of Same Resource or Handle,Base,Incomplete,The product attempts to close or release a res...,Code typically requires opening handles or ref...,::NATURE:ChildOf:CWE ID:675:VIEW ID:1000:ORDIN...,::ORDINALITY:Resultant::,::LANGUAGE NAME:Java:LANGUAGE PREVALENCE:Undet...,NaN,NaN,...,::SCOPE:Availability:SCOPE:Integrity:IMPACT:Do...,::METHOD:Automated Static Analysis:DESCRIPTION...,::PHASE:Implementation:DESCRIPTION:Change the ...,::REFERENCE:CVE-2019-13351:DESCRIPTION:file de...,NaN,NaN,NaN,NaN,::TYPE:Terminology:NOTE:The terms related to r...,NaN
1389,Incorrect Parsing of Numbers with Different Ra...,Base,Incomplete,The product parses numeric input assuming base...,"Frequently, a numeric input that begins with 0...",::NATURE:ChildOf:CWE ID:704:VIEW ID:1000:ORDIN...,::ORDINALITY:Primary::,::LANGUAGE CLASS:Not Language-Specific:LANGUAG...,NaN,NaN,...,::SCOPE:Confidentiality:IMPACT:Read Applicatio...,::METHOD:Automated Static Analysis:DESCRIPTION...,::PHASE:Implementation:STRATEGY:Enforcement by...,::REFERENCE:CVE-2021-29662:DESCRIPTION:Chain: ...,NaN,NaN,NaN,NaN,NaN,NaN
1392,Use of Default Credentials,Base,Incomplete,The product uses default credentials (such as ...,It is common practice for products to be desig...,::NATURE:ChildOf:CWE ID:1391:VIEW ID:1000:ORDI...,::ORDINALITY:Primary::,::LANGUAGE CLASS:Not Language-Specific:LANGUAG...,NaN,NaN,...,::SCOPE:Authentication:IMPACT:Gain Privileges ...,NaN,::PHASE:Requirements:DESCRIPTION:Prohibit use ...,::REFERENCE:CVE-2022-30270:DESCRIPTION:Remote ...,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
#to display only the row id 15
df.iloc[15]

CWE-ID                                                Missing XML Validation
Name                                                                    Base
Weakness Abstraction                                                   Draft
Status                     The product accepts XML from an untrusted sour...
Description                Most successful attacks begin with a violation...
Extended Description       ::NATURE:ChildOf:CWE ID:1286:VIEW ID:1000:ORDI...
Related Weaknesses                                    ::ORDINALITY:Primary::
Weakness Ordinalities      ::LANGUAGE CLASS:Not Language-Specific:LANGUAG...
Applicable Platforms                                                     NaN
Background Details                                                       NaN
Alternate Terms                                     ::PHASE:Implementation::
Modes Of Introduction                                                    NaN
Exploitation Factors                                                     NaN
Likelihood of Exploit            ::SCOPE:Integrity:IMPACT:Unexpected State::
Common Consequences        ::METHOD:Automated Static Analysis:DESCRIPTION...
Detection Methods          ::PHASE:Architecture and Design:STRATEGY:Input...
Potential Mitigations                                                    NaN
Observed Examples                                                        NaN
Functional Areas                                                         NaN
Affected Resources         ::TAXONOMY NAME:7 Pernicious Kingdoms:ENTRY NA...
Taxonomy Mappings                                               ::230::231::
Related Attack Patterns                                                  NaN
Notes                                                                    NaN
Name: 112, dtype: object

In [ ]:
#with pd.option_context('display.max_rows', None, 'display.max_columns', None): print(df)
pd.set_option('display.max_rows', None, 'display.max_columns', None)

In [ ]:
df[df["Description"].str.contains('auth',case=False,na=False)]

,CWE-ID,Name,Weakness Abstraction,Status,Description,Extended Description,Related Weaknesses,Weakness Ordinalities,Applicable Platforms,Background Details,Alternate Terms,Modes Of Introduction,Exploitation Factors,Likelihood of Exploit,Common Consequences,Detection Methods,Potential Mitigations,Observed Examples,Functional Areas,Affected Resources,Taxonomy Mappings,Related Attack Patterns,Notes
301,Reflection Attack in an Authentication Protocol,Base,Draft,Simple authentication protocols are subject to...,A mutual authentication protocol requires each...,::NATURE:ChildOf:CWE ID:1390:VIEW ID:1000:ORDI...,::ORDINALITY:Resultant::,::LANGUAGE CLASS:Not Language-Specific:LANGUAG...,NaN,NaN,::PHASE:Architecture and Design:NOTE:COMMISSIO...,NaN,NaN,::SCOPE:Access Control:IMPACT:Gain Privileges ...,NaN,::PHASE:Architecture and Design:DESCRIPTION:Us...,::REFERENCE:CVE-2005-3435:DESCRIPTION:product ...,NaN,NaN,::TAXONOMY NAME:CLASP:ENTRY NAME:Reflection at...,::90::,::TYPE:Maintenance:NOTE:The term reflection is...,NaN
303,Incorrect Implementation of Authentication Alg...,Base,Draft,The requirements for the product dictate the u...,This incorrect implementation may allow authen...,::NATURE:ChildOf:CWE ID:1390:VIEW ID:1000:ORDI...,::ORDINALITY:Primary::,::LANGUAGE CLASS:Not Language-Specific:LANGUAG...,NaN,NaN,::PHASE:Implementation:NOTE:REALIZATION: This ...,NaN,NaN,::SCOPE:Access Control:IMPACT:Bypass Protectio...,NaN,NaN,::REFERENCE:CVE-2003-0750:DESCRIPTION:Conditio...,NaN,NaN,::TAXONOMY NAME:PLOVER:ENTRY NAME:Authenticati...,::90::,NaN,NaN
322,Key Exchange without Entity Authentication,Base,Draft,The product performs a key exchange with an ac...,Performing a key exchange will preserve the in...,::NATURE:ChildOf:CWE ID:306:VIEW ID:1000:ORDIN...,::ORDINALITY:Primary::,::LANGUAGE CLASS:Not Language-Specific:LANGUAG...,NaN,NaN,::PHASE:Architecture and Design:NOTE:OMISSION:...,NaN,NaN,::SCOPE:Access Control:IMPACT:Bypass Protectio...,::METHOD:Automated Static Analysis:DESCRIPTION...,::PHASE:Architecture and Design:DESCRIPTION:En...,NaN,NaN,NaN,::TAXONOMY NAME:CLASP:ENTRY NAME:Key exchange ...,NaN,NaN,NaN
360,Trust of System Event Data,Base,Incomplete,Security based on event locations are insecure...,Events are a messaging system which may provid...,::NATURE:ChildOf:CWE ID:345:VIEW ID:1000:ORDIN...,::ORDINALITY:Primary::,::LANGUAGE CLASS:Not Language-Specific:LANGUAG...,NaN,NaN,::PHASE:Architecture and Design::PHASE:Impleme...,NaN,NaN,::SCOPE:Integrity:SCOPE:Confidentiality:SCOPE:...,NaN,::PHASE:Architecture and Design:DESCRIPTION:Ne...,::REFERENCE:CVE-2004-0213:DESCRIPTION:Attacker...,NaN,NaN,::TAXONOMY NAME:CLASP:ENTRY NAME:Trust of syst...,NaN,NaN,NaN
421,Race Condition During Access to Alternate Channel,Base,Draft,The product opens an alternate channel to comm...,This creates a race condition that allows an a...,::NATURE:ChildOf:CWE ID:420:VIEW ID:1000:ORDIN...,::ORDINALITY:Primary::,::LANGUAGE CLASS:Not Language-Specific:LANGUAG...,NaN,NaN,::PHASE:Architecture and Design::,NaN,NaN,::SCOPE:Access Control:IMPACT:Gain Privileges ...,NaN,NaN,::REFERENCE:CVE-1999-0351:DESCRIPTION:FTP Pizz...,::Program Invocation::,::System Process::,::TAXONOMY NAME:PLOVER:ENTRY NAME:Alternate Ch...,NaN,NaN,NaN
425,Direct Request ('Forced Browsing'),Base,Incomplete,The web application does not adequately enforc...,Web applications susceptible to direct request...,::NATURE:ChildOf:CWE ID:862:VIEW ID:1000:ORDIN...,::ORDINALITY:Primary::,::LANGUAGE CLASS:Not Language-Specific:LANGUAG...,NaN,::TERM:forced browsing:DESCRIPTION:The forced ...,::PHASE:Implementation::PHASE:Operation::,NaN,NaN,::SCOPE:Confidentiality:SCOPE:Integrity:SCOPE:...,NaN,::PHASE:Architecture and Design Operation:DESC...,::REFERENCE:CVE-2022-29238:DESCRIPTION:Access-...,NaN,NaN,::TAXONOMY NAME:PLOVER:ENTRY NAME:Direct Reque...,::127::143::144::668::87::,::TYPE:Relationship:NOTE:Overlaps Modification...,NaN
426,Untrusted Search Path,Base,Stable,The product searches for critical resources us...,This might allow attackers to execute their ow...,::NATURE:ChildOf:CWE ID:642:VIEW ID:1000:ORDIN...,::ORDINALITY:Primary::,::LANGUAGE CLASS:Not Language-Specific:LANGUAG...,NaN,::TERM:Untrusted Path::,::PHASE:Implementation::,NaN,NaN,::SCOPE:Integrity:SCOPE:Confidentiality:SCOPE:...,::METHOD:Black Box:DESCRIPTION:Use monitoring ...,::PHASE:Architecture and Design Implementation...,::REFERENCE:CVE-1999-1120:DESCRIPTION:Applicat...,::Program Invocation::Code Libraries::,::System Process::,::TAXONOMY NAME:PLOVER:ENTRY NAME:Untrusted Se...,::38::,NaN,NaN
470,Use of Externally-Controlled Input to Select C...,Base,Draft,The product uses external input with reflectio...,If the product uses external inputs to determi...,::NATURE:ChildOf:CWE ID:913:VIEW ID:1000:ORDIN...,::ORDINALITY:Primary::,::LANGUAGE NAME:Java:LANGUAGE PREVALENCE:Undet...,NaN,::TERM:Reflection Injection::,::PHASE:Architecture and Design::PHASE:Impleme...,NaN,NaN,::SCOPE:Integrity:SCOPE:Confidentiality:SCOPE:...,::METHOD:Automated Static Analysis:DESCRIPTION...,::PHASE:Architecture and Design:DESCRIPTION:Re...,::REFERENCE:CVE-2018-1000613:DESCRIPTION:Crypt...,NaN,NaN,::TAXONOMY NAME:7 Pernicious Kingdoms:ENTRY NA...,::138::,NaN,NaN
472,External Control of Assumed-Immutable Web Para...,Base,Draft,The web application does not sufficiently veri...,If a web product does not properly protect ass...,::NATURE:ChildOf:CWE ID:642:VIEW ID:1000:ORDIN...,::ORDINALITY:Primary::ORDINALITY:Resultant::,::LANGUAGE CLASS:Not Language-Specific:LANGUAG...,NaN,::TERM:Assumed-Immutable Parameter Tampering::,::PHASE:Implementation:NOTE:OMISSION: This wea...,NaN,NaN,::SCOPE:Integrity:IMPACT:Modify Application Da...,::METHOD:Automated Static Analysis:DESCRIPTION...,::PHASE:Implementation:STRATEGY:Input Validati...,::REFERENCE:CVE-2002-0108:DESCRIPTION:Forum pr...,NaN,NaN,::TAXONOMY NAME:PLOVER:ENTRY NAME:Web Paramete...,::146::226::31::39::,::TYPE:Relationship:NOTE:This is a primary wea...,NaN
497,Exposure of Sensitive System Information to an...,Base,Incomplete,The product does not properly prevent sensitiv...,"Network-based products, such as web applicatio...",::NATURE:ChildOf:CWE ID:200:VIEW ID:1000:ORDIN...,::ORDINALITY:Primary::ORDINALITY:Resultant::,::LANGUAGE CLASS:Not Language-Specific:LANGUAG...,NaN,NaN,::PHASE:Implementation::,NaN,NaN,::SCOPE:Confidentiality:IMPACT:Read Applicatio...,::METHOD:Automated Static Analysis:DESCRIPTION...,::PHASE:Architecture and Design Implementation...,::REFERENCE:CVE-2021-32638:DESCRIPTION:Code an...,NaN,NaN,::TAXONOMY NAME:7 Pernicious Kingdoms:ENTRY NA...,::170::694::,NaN,NaN
524,Use of Cache Containing Sensitive Information,Base,Incomplete,The code uses a cache that contains sensitive ...,Applications may use caches to improve efficie...,::NATURE:ChildOf:CWE ID:668:VIEW ID:1000:ORDIN...,::ORDINALITY:Primary::,::LANGUAGE CLASS:Not Language-Specific:LANGUAG...,NaN,NaN,::PHASE:Implementation::,NaN,NaN,::SCOPE:Confidentiality:IMPACT:Read Applicatio...,::METHOD:Automated Static Analysis:DESCRIPTION...,::PHASE:Architecture and Design:DESCRIPTION:Pr...,NaN,NaN,NaN,NaN,::204::,NaN,NaN
551,Incorrect Behavior Order: Authorization Before...,Base,Incomplete,If a web server does not fully parse requested...,"For instance, the character strings /./ and / ...",::NATURE:ChildOf:CWE ID:863:VIEW ID:1000:ORDIN...,::ORDINALITY:Primary::,::LANGUAGE CLASS:Not Language-Specific:LANGUAG...,NaN,NaN,::PHASE:Implementation:NOTE:REALIZATION: This ...,NaN,NaN,::SCOPE:Access Control:IMPACT:Bypass Protectio...,NaN,::PHASE:Architecture and Design:DESCRIPTION:UR...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
603,Use of Client-Side Authentication,Base,Draft,A client/server product performs authenticatio...,Client-side authentication is extremely weak a...,::NATURE:ChildOf:CWE ID:1390:VIEW ID:1000:ORDI...,::ORDINALITY:Primary::,::LANGUAGE CLASS:Not Language-Specific:LANGUAG...,NaN,NaN,::PHASE:Architecture and Design:NOTE:COMMISSIO...,NaN,NaN,::SCOPE:Access Control:IMPACT:Bypass Protectio...,NaN,::PHASE:Architecture and Design:DESCRIPTION:Do...,::REFERENCE:CVE-2022-33139:DESCRIPTION:SCADA s...,NaN,NaN,NaN,NaN,NaN,NaN
639,Authorization Bypass Through User-Controlled Key,Base,Incomplete,The system's authorization functionality does ...,Retrieval of a user record occurs in the syste...,::NATURE:ChildOf:CWE ID:863:VIEW ID:1000:ORDIN...,::ORDINALITY:Primary::ORDINALITY:Resultant::,::LANGUAGE CLASS:Not Language-Specific:LANGUAG...,NaN,::TERM:Insecure Direct Object Reference / IDOR...,::PHASE:Architecture and Design:NOTE:REALIZATI...,NaN,NaN,::SCOPE:Access Control:IMPACT:Bypass Protectio...,::METHOD:Automated Static Analysis:DESCRIPTION...,::PHASE:Architecture and Design:DESCRIPTION:Fo...,::REFERENCE:CVE-2021-36539:DESCRIPTION:An educ...,NaN,NaN,NaN,NaN,NaN,NaN
640,Weak Password Recovery Mechanism for Forgotten...,Base,Incomplete,The product contains a mechanism for users to ...,It is common for an application to have a mech...,::NATURE:ChildOf:CWE ID:1390:VIEW ID:1000:ORDI...,::ORDINALITY:Primary::,::LANGUAGE CLASS:Not Language-Specific:LANGUAG...,NaN,NaN,::PHASE:Architecture and Design:NOTE:COMMISSIO...,NaN,NaN,::SCOPE:Access Control:IMPACT:Gain Privileges ...,NaN,::PHASE:Architecture and Design:DESCRIPTION:Ma...,NaN,NaN,NaN,::TAXONOMY NAME:WASC:ENTRY ID:49:ENTRY NAME:In...,::50::,::TYPE:Maintenance:NOTE:This entry might be re...,NaN
645,Overly Restrictive Account Lockout Mechanism,Base,Incomplete,The product contains an account lockout protec...,Account lockout is a security feature often pr...,::NATURE:ChildOf:CWE ID:287:VIEW ID:1000:ORDIN...,::ORDINALITY:Primary::,::LANGUAGE CLASS:Not Language-Specific:LANGUAG...,NaN,NaN,::PHASE:Architecture and Design:NOTE:COMMISSIO...,NaN,NaN,::SCOPE:Availability:IMPACT:DoS: Resource Cons...,NaN,::PHASE:Architecture and Design:DESCRIPTION:Im...,NaN,NaN,NaN,NaN,::2::,NaN,NaN
783,Operator Precedence Logic Error,Base,Draft,The product uses an expression in which operat...,"While often just a bug, operator precedence lo...",::NATURE:ChildOf:CWE ID:670:VIEW ID:1000:ORDIN...,::ORDINALITY:Primary::,::LANGUAGE NAME:C:LANGUAGE PREVALENCE:Rarely::...,NaN,NaN,::PHASE:Implementation:NOTE:Logic errors relat...,NaN,NaN,::SCOPE:Confidentiality:SCOPE:Integrity:SCOPE:...,::METHOD:Automated Static Analysis:DESCRIPTION...,::PHASE:Implementation:DESCRIPTION:Regularly w...,::REFERENCE:CVE-2008-2516:DESCRIPTION:Authenti...,NaN,NaN,::TAXONOMY NAME:CERT C Secure Coding:ENTRY ID:...,NaN,NaN,NaN
798,Use of Hard-coded Credentials,Base,Draft,"The product contains hard-coded credentials, s...",There are two main variations: Inbound: the pr...,::NATURE:ChildOf:CWE ID:1391:VIEW ID:1000:ORDI...,::ORDINALITY:Primary::,::LANGUAGE CLASS:Not Language-Specific:LANGUAG...,NaN,NaN,::PHASE:Architecture and Design:NOTE:REALIZATI...,NaN,NaN,::SCOPE:Access Control:IMPACT:Bypass Protectio...,::METHOD:Black Box:DESCRIPTION:Credential stor...,::PHASE:Architecture and Design:DESCRIPTION:Fo...,::REFERENCE:CVE-2022-40263:DESCRIPTION:Softwar...,NaN,NaN,::TAXONOMY NAME:The CERT Oracle Secure Coding ...,::191::70::,NaN,NaN
807,Reliance on Untrusted Inputs in a Security Dec...,Base,Incomplete,The product uses a protection mechanism that r...,Developers may assume that inputs such as cook...,::NATURE:ChildOf:CWE ID:693:VIEW ID:1000:ORDIN...,::ORDINALITY:Primary::,::LANGUAGE CLASS:Not Language-Specific:LANGUAG...,NaN,NaN,::PHASE:Architecture and Design:NOTE:COMMISSIO...,NaN,NaN,::SCOPE:Confidentiality:SCOPE:Access Control:S...,::METHOD:Manual Static Analysis:DESCRIPTION:Si...,::PHASE:Architecture and Design:STRATEGY:Attac...,::REFERENCE:CVE-2009-1549:DESCRIPTION:Attacker...,NaN,NaN,::TAXONOMY NAME:The CERT Oracle Secure Coding ...,NaN,NaN,NaN
836,Use of Password Hash Instead of Password for A...,Base,Incomplete,The product records password hashes in a data ...,Some authentication mechanisms rely on the cli...,::NATURE:ChildOf:CWE ID:1390:VIEW ID:1000:ORDI...,::ORDINALITY:Primary::,::LANGUAGE CLASS:Not Language-Specific:LANGUAG...,NaN,NaN,::PHASE:Implementation:NOTE:REALIZATION: This ...,NaN,NaN,::SCOPE:Access Control:IMPACT:Bypass Protectio...,NaN,NaN,::REFERENCE:CVE-2009-1283:DESCRIPTION:Product ...,NaN,NaN,NaN,::644::652::,NaN,NaN
916,Use of Password Hash With Insufficient Computa...,Base,Incomplete,"The product generates a hash for a password, b...",Many password storage mechanisms compute a has...,::NATURE:ChildOf:CWE ID:328:VIEW ID:1000:ORDIN...,::ORDINALITY:Primary::,::LANGUAGE CLASS:Not Language-Specific:LANGUAG...,NaN,NaN,::PHASE:Architecture and Design:NOTE:REALIZATI...,NaN,NaN,::SCOPE:Access Control:IMPACT:Bypass Protectio...,::METHOD:Automated Static Analysis - Binary or...,::PHASE:Architecture and Design:DESCRIPTION:Us...,::REFERENCE:CVE-2008-1526:DESCRIPTION:Router d...,NaN,NaN,NaN,::55::,NaN,NaN
1115,Source Code Element without Standard Prologue,Base,Incomplete,The source code contains elements such as sour...,Standard prologues or headers may contain info...,::NATURE:ChildOf:CWE ID:1078:VIEW ID:1000:ORDI...,::ORDINALITY:Indirect::,::LANGUAGE CLASS:Not Language-Specific:LANGUAG...,NaN,NaN,::PHASE:Implementation::,NaN,NaN,::SCOPE:Other:IMPACT:Reduce Maintainability:NO...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1230,Exposure of Sensitive Information Through Meta...,Base,Incomplete,The product prevents direct access to a resour...,Developers might correctly prevent unauthorize...,::NATURE:ChildOf:CWE ID:285:VIEW ID:1000:ORDIN...,::ORDINALITY:Primary::ORDINALITY:Resultant::,::LANGUAGE CLASS:Not Language-Specific:LANGUAG...,NaN,NaN,::PHASE:Architecture and Design::,NaN,NaN,::SCOPE:Confidentiality:IMPACT:Read Applicatio...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1285,"Improper Validation of Specified Index, Positi...",Base,Incomplete,The product receives input that is expected to...,"Often, indexable resources such as memory buff...",::NATURE:ChildOf:CWE ID:20:VIEW ID:1000:ORDINA...,::ORDINALITY:Primary::,::LANGUAGE CLASS:Not Language-Specific:LANGUAG...,NaN,NaN,::PHASE:Implementation::,NaN,NaN,::SCOPE:Other:IMPACT:Varies by Context::,::METHOD:Automated Static Analysis:DESCRIPTION...,::PHASE:Implementation:STRATEGY:Input Validati...,::REFERENCE:CVE-2005-0369:DESCRIPTION:large ID...,NaN,NaN,NaN,NaN,::TYPE:Maintenance:NOTE:This entry is still un...,NaN
1392,Use of Default Credentials,Base,Incomplete,The product uses default credentials (such as ...,It is common practice for products to be desig...,::NATURE:ChildOf:CWE ID:1391:VIEW ID:1000:ORDI...,::ORDINALITY:Primary::,::LANGUAGE CLASS:Not Language-Specific:LANGUAG...,NaN,NaN,::PHASE:Architecture and Design::,NaN,NaN,::SCOPE:Authentication:IMPACT:Gain Privileges ...,NaN,::PHASE:Requirements:DESCRIPTION:Prohibit use ...,::REFERENCE:CVE-2022-30270:DESCRIPTION:Remote ...,NaN,NaN,NaN,NaN,NaN,NaN